### ISSUE TITLE
how to use??

### ISSUE THREAD

**Issue by zengleyi** [riclolsen/OSHMI#1]
how to use? execute it.

**Comment by riclolsen** [comment]
Hi!
Download the binary release from here
https://sourceforge.net/projects/oshmiopensubstationhmi/

**Comment by wanarta** [comment]
How about for linux, as the binary only for windows?

**Comment by riclolsen** [comment]
The binaries are Windows only, but it can run in Linux under Wine.
Most modules can be compiled on Linux or installed natively.
There are instructions in the configuration manual on how to run on Linux.
