### ISSUE TITLE
How to use it through browser?

### ISSUE THREAD

**Issue by xujingzhou** [riclolsen/OSHMI#2]
Hi, there has H5 + JS(TS) version?  how to compile it.

**Comment by riclolsen** [comment]
Hi!
The user interface is HTML5, viewers are HTML5 apps opened in an embedded Chromium browser.
You can open by default on a browser in the local machine http://127.0.0.1:51909.
Build requirements are here
https://github.com/riclolsen/OSHMI/blob/master/installer/release_notes.txt
Best regards.
