### ISSUE TITLE
OSHMI Traffic 

### ISSUE THREAD

**Issue by Taco12** [riclolsen/OSHMI#4]
Hello Ricardo, I'm trying to replicate a SCADA netwrok with OSHMI, IECServer and Qtester104. I've each software in singles machines, and i've connected IEC server with Qtester, but i dont know how to connect with OSHMI. Im using VirtualBOX and i need to generate SCADA traffic with OSHMI. 
Thanks for your time!!

**Comment by riclolsen** [comment]
Hi Taco!
OSHMI has an integrated QTester104. Configure the qtester104.ini file in the c:\oshmi\conf\ folder.
To see data in OSHMI you must configure c:\oshmi\conf\point_list.txt with all the points you want to monitor. See the configuration manual to understand this file.
After configured, run QTester104.exe and webserver.exe from the c:\oshmi\bin\ folder.
Best regards,
Ricardo
