### ISSUE TITLE
How to update parameter using IEC104 from scada ?

### ISSUE THREAD

**Issue by pungkursari1088** [riclolsen/OSHMI#5]
hello, i want to ask how to send parameter to change digital input on scada to RTU using IEC 104 ? 
I try using top.WebSAGE.directCommandExec(64165, "ON"); but the parameter didnt update and not sending to RTU 
![Capture](https://user-images.githubusercontent.com/20756492/92896225-65bd1500-f446-11ea-84f2-976d06707b91.JPG)
from qtester104. parameter that i want to transmit (grey colour) didnt transmit using standart protocol.

**Comment by riclolsen** [comment]
Hi,
What is the command message you need to send? Type 45, 46, or some other?
You must have the command point defined in point_list.txt with parameters OR=7, ASDU=45 (or 46) and RTU=rtu_address. Please check this.
If you still have problems, please post your point_list.txt.

**Comment by pungkursari1088** [comment]
didnt know that we need check ASDU to send message 
you're really big help, 
Thank you
